### ISSUE TITLE
Forget to set the query type of `snd_seq_query_subscribe_t` before calling `snd_seq_query_port_subscribers()`

### ISSUE THREAD

**Issue by Zero0one1** [tedfelix/rosegarden-official#1]
According to the ALSA library document of [`snd_seq_query_port_subscribers()`](https://www.alsa-project.org/alsa-doc/alsa-lib/group___seq_subscribe.html#gac9c05af9bb647d1aa9b4408f571c809d), we need to set the client, port, index, query type of the second parameter `subs`, whose type is `snd_seq_query_subscribe_t`, using corresponding APIs.

> At least, the client id, the port id, the index number and the query type must be set to perform a proper query.

However, `subs` in L4970 lacks the query type set using [`snd_seq_query_subscribe_set_type()`](https://www.alsa-project.org/alsa-doc/alsa-lib/group___seq_subscribe.html#gad78be14f613420a840ef0fc3ebdf3740).

https://github.com/tedfelix/rosegarden-official/blob/585e2b5f6cde78a9fa767210fac85e5bb121a293/src/sound/AlsaDriver.cpp#L4958-L4970

**Comment by tedfelix** [comment]
So, sounds like we need the following, perhaps after L4960:

    snd_seq_query_subscribe_set_type(subs, SND_SEQ_QUERY_SUBS_READ);

I assume it has been working because SND_SEQ_QUERY_SUBS_READ is 0 and that's likely the value that is in the struct by default.  And since we're just reading, even if it were "WRITE" it would still work fine.

This makes me wonder whether the two uses of SND_SEQ_QUERY_SUBS_WRITE are actually correct in this file.  The one in `AlsaDriver::isRecording()` seems wrong.  There's no writing going on here.  The one in `AlsaDriver::unsetRecordDevices()` seems wrong as well since there is no *direct* writing here.  Thoughts?

**Comment by Zero0one1** [comment]
> I assume it has been working because SND_SEQ_QUERY_SUBS_READ is 0 and that's likely the value that is in the struct by default. And since we're just reading, even if it were "WRITE" it would still work fine.

I'm not familiar with the ALSA library, but I think you're right.

I looked into `AlsaDriver::isRecording()` and `AlsaDriver::unsetRecordDevices()` and didn't see writing. Maybe we should change it to `SND_SEQ_QUERY_SUBS_READ`. Also, I wonder which API can be used to write. Do you know that?

**Comment by tedfelix** [comment]
> I wonder which API can be used to write.

Looks like there are a number of `snd_seq_port_subscribe_set_*()` functions that do that.

A search for `port_subscribe_set` finds exactly four calls in AlsaDriver.cpp.  Two in `setRecordDevice()` and two in `unsetRecordDevices()`.  So `isrecording()` very likely doesn't need SND_SEQ_QUERY_SUBS_WRITE and `unsetRecordDevices()` probably does.  (`setRecordDevice()` doesn't iterate, so it's not an issue.)

**Comment by Zero0one1** [comment]
> Looks like there are a number of snd_seq_port_subscribe_set_*() functions that do that.

I got a question: `snd_seq_port_subscribe_set_*()` take `snd_seq_port_subscribe_t` type as parameter, while `SND_SEQ_QUERY_SUBS_READ` is one field of `snd_seq_query_subscribe_t`. Looks like `snd_seq_port_subscribe_set_*()` can't perform writing for `snd_seq_query_subscribe_t`. 

So I read the [ALSA document for the subscription part](https://www.alsa-project.org/alsa-doc/alsa-lib/seq.htm) but didn't find the explanation for the query. Then I looked into the structure of `snd_seq_port_subscribe_t` and `snd_seq_query_subscribe_t` but didn't have any clue of the relationship between them. Do you know their relation?
Their structures: https://github.com/alsa-project/alsa-lib/blob/master/include/sound/uapi/asequencer.h#L546-L569

**Comment by tedfelix** [comment]
Ok, I think I was very wrong before.

SND_SEQ_QUERY_SUBS_WRITE means to query the subscribers that are configured for WRITE (record?).  It has nothing to do with "write permissions" as I originally thought.

I'm in the process of reviewing and cleaning up AlsaDriver::isRecord() and should have an easier to understand version shortly...

**Comment by tedfelix** [comment]
Ok, so it turns out isRecording() isn't called by anyone.  Argh.  🙄  Wasting time here.  I'm going to look for another SND_SEQ_QUERY_SUBS_WRITE routine to review...  But I do think I'm on the right track now.  SND_SEQ_QUERY_SUBS_WRITE means to query the connected (subscribed) port writers.  Those that are connected to an input port.

**Comment by tedfelix** [comment]
So it turns out that only `AlsaDriver::configureExternalControllerPort()` calls snd_seq_query_subscribe_set_type() and is actually used in Rosegarden.  And it doesn't really do anything interesting other than query the number of READ subscribers (MIDI controllers connected) to a port to see if it is already connected to something.  I'm going to have a closer look at checkForNewClients() now that I'm getting a better understanding of all this.  Hopefully I'll be able to answer your original questions shortly.

(The source for [aconnect](https://github.com/alsa-project/alsa-utils/blob/master/seq/aconnect/aconnect.c) is a better place to look for examples of how to use all this.)

Ok, I've actually just reviewed the key portion of `checkForNewClients()`, fixed the bug you identified and added some comments.  Here's the new version that should be a lot clearer, I hope:

```
snd_seq_query_subscribe_t *subs;
// On stack, so no need to free.
snd_seq_query_subscribe_alloca(&subs);
// Search only for readers (MIDI synths).
snd_seq_query_subscribe_set_type(subs, SND_SEQ_QUERY_SUBS_READ);
// Connected to the current "device" (MIDI output port).
snd_seq_query_subscribe_set_root(subs, &addr);
// Start at subscriber number 0.
snd_seq_query_subscribe_set_index(subs, 0);
```

So, it was indeed working fine simply because snd_seq_query_subscribe_alloca() zeroes out the memory and READ is 0 and READ is what we wanted.

Now let me take a look at your second set of questions and see if I can straighten out the confusion that I initially caused...

**Comment by tedfelix** [comment]
> I got a question: `snd_seq_port_subscribe_set_*()` take `snd_seq_port_subscribe_t` type as parameter,

Correct.

> while `SND_SEQ_QUERY_SUBS_READ` is one field of `snd_seq_query_subscribe_t`.

`SND_SEQ_QUERY_SUBS_READ` can be used for the `type` field.  But we should always use `snd_seq_port_subscribe_set_type()` to set this.

> Looks like `snd_seq_port_subscribe_set_*()` can't perform writing for `snd_seq_query_subscribe_t`.

Correct.  To write to a snd_seq_query_subscribe_t, you would need to use the `snd_seq_query_subscribe_set_*()` routines.  There is a pattern to this, fortunately.  A lot of the terminology is pretty confusing though.  Like "read subscriber" to mean "something connected to an output port".  This is what consistently trips me up and causes me to give bad advice.

> So I read the [ALSA document for the subscription part](https://www.alsa-project.org/alsa-doc/alsa-lib/seq.htm) but didn't find the explanation for the query. Then I looked into the structure of `snd_seq_port_subscribe_t` and `snd_seq_query_subscribe_t` but didn't have any clue of the relationship between them. Do you know their relation?

Now (I think) I do...

A `snd_seq_port_subscribe_t` describes a connection between two ports (sender and dest).  It can be used with `snd_seq_subscribe_port()` to make a connection.

A `snd_seq_query_subscribe_t` describes a connection query (root port, type, index) and holds the result of that query (port addr).  It is used to select which connection will be returned by `snd_seq_query_port_subscribers()`.  It's like an iterator in C++.

They are related only in that they can both be used to work with connections between ports.

**Comment by Zero0one1** [comment]
Ok, I read the [aconnect ](https://github.com/alsa-project/alsa-utils/blob/master/seq/aconnect/aconnect.c)code and think I almost get it. Let me choose an example and test if I really understand.

`AlsaDriver::isRecording` checks if the `port` of one client(let's use the microphone) is recording the sound, which can be sent to other clients. It means that the `port` has `READ` permission(it can be read by other clients), so the type of `qSubs` should be `SND_SEQ_QUERY_SUBS_READ` . 
https://github.com/tedfelix/rosegarden-official/blob/585e2b5f6cde78a9fa767210fac85e5bb121a293/src/sound/AlsaDriver.cpp#L4877-L4908

**Comment by tedfelix** [comment]
isRecording() is unused code, so I'm not sure that it works at all.  That said...

The read/write is from the subscriber's (connected MIDI device's) perspective.  So it is the opposite of what you are thinking.  With helpful comments:

    // Query write subscribers.  Those that can write to the port.
    // This would usually be MIDI keyboards.
    snd_seq_query_subscribe_set_type(qSubs, SND_SEQ_QUERY_SUBS_WRITE);
    // Connected to the rosegarden input port.
    snd_seq_query_subscribe_set_root(qSubs, &rg_addr); 

So isRecording() is checking whether a specific ALSA MIDI port (`port`) is connected to Rosegarden's MIDI input port for WRITE access.  A better name for this routine would be "isConnectedForRecord()".

Read/write, input/output is always really easy to get mixed up since the perspective changes things.  It's quite annoying.

**Comment by Zero0one1** [comment]
Oh, I misunderstood maybe because I don't know the high-level idea of the `isRecording()`.

In short, the ALSA MIDI port (`port`) is the one to record, while Rosegarden's MIDI input port writes something to `port`. So the subscription to `port`  needs WRITE access. Right? 🤔

**Comment by tedfelix** [comment]
> Oh, I misunderstood maybe because I don't know the high-level idea of the isRecording().

`isRecording()` is checking to see if `port` is connected (subscribed) for WRITE access to Rosegarden's input port.

> In short, the ALSA MIDI port (port) is the one to record,

Correct.  It's most likely a MIDI keyboard connected to the computer via USB.

> while Rosegarden's MIDI input port writes something to port.

Other way around.  `port` writes to Rosegarden's MIDI input port (`m_inputPort`).

> So the subscription to port needs WRITE access. Right?

A "subscription" is a potentially bidirectional connection, which is a strange abuse of the word subscription which usually means unidirectional.  Since the keyboard (`port`) wants to write to Rosegarden (`m_inputPort`) it indicates that it needs WRITE access when it subscribes (connects).

**Comment by Zero0one1** [comment]
Got it. Thanks a lot for your explanation. I think we can close the issue now. 😄
